/* OBSYRA CAREER PORTAL - PRODUCTION CONFIGURATION */
const CONFIG = {
  // PASTE YOUR GOOGLE APPS SCRIPT WEB APP URL HERE AFTER DEPLOYMENT
  API_URL: 'YOUR_GOOGLE_APPS_SCRIPT_WEB_APP_URL',
  
  COMPANY_NAME: 'Obsyra Pvt Ltd',
  COMPANY_LOCATION: 'Wagholi, Pune, Maharashtra, India',
  SUPPORT_EMAIL: 'careers@obsyra.com',
  SUPPORT_WHATSAPP: '919876543210',
  
  ENABLE_MOCK_FALLBACK: true,
  VERSION: '4.2.0'
};
